package com.courseplatform.dao;

import com.courseplatform.bean.Courseware;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface CoursewareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    @Delete({
            "delete from courseware",
            "where courseware_id = #{coursewareId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String coursewareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    @Insert({
            "insert into courseware (courseware_id, course_id, ",
            "teacher_account, courseware_name, ",
            "file_path)",
            "values (#{coursewareId,jdbcType=VARCHAR}, #{courseId,jdbcType=VARCHAR}, ",
            "#{teacherAccount,jdbcType=VARCHAR}, #{coursewareName,jdbcType=VARCHAR}, ",
            "#{filePath,jdbcType=VARCHAR})"
    })
    int insert(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    @Select({
            "select",
            "courseware_id, course_id, teacher_account, courseware_name, file_path",
            "from courseware",
            "where courseware_id = #{coursewareId,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column = "courseware_id", property = "coursewareId", jdbcType = JdbcType.VARCHAR, id = true),
            @Result(column = "course_id", property = "courseId", jdbcType = JdbcType.VARCHAR),
            @Result(column = "teacher_account", property = "teacherAccount", jdbcType = JdbcType.VARCHAR),
            @Result(column = "courseware_name", property = "coursewareName", jdbcType = JdbcType.VARCHAR),
            @Result(column = "file_path", property = "filePath", jdbcType = JdbcType.VARCHAR)
    })
    Courseware selectByPrimaryKey(String coursewareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    @Select({
            "select",
            "courseware_id, course_id, teacher_account, courseware_name, file_path",
            "from courseware"
    })
    @Results({
            @Result(column = "courseware_id", property = "coursewareId", jdbcType = JdbcType.VARCHAR, id = true),
            @Result(column = "course_id", property = "courseId", jdbcType = JdbcType.VARCHAR),
            @Result(column = "teacher_account", property = "teacherAccount", jdbcType = JdbcType.VARCHAR),
            @Result(column = "courseware_name", property = "coursewareName", jdbcType = JdbcType.VARCHAR),
            @Result(column = "file_path", property = "filePath", jdbcType = JdbcType.VARCHAR)
    })
    List<Courseware> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    @Update({
            "update courseware",
            "set course_id = #{courseId,jdbcType=VARCHAR},",
            "teacher_account = #{teacherAccount,jdbcType=VARCHAR},",
            "courseware_name = #{coursewareName,jdbcType=VARCHAR},",
            "file_path = #{filePath,jdbcType=VARCHAR}",
            "where courseware_id = #{coursewareId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Courseware record);

    List<Courseware> selectByCourseIdAndTeacherAccount(@Param("courseId") String courseId, @Param("teacherAccount") String teacherAccount);

    int insertCoursewares(@Param("coursewares") List<Courseware> coursewares);

}