package com.courseplatform.dao;

import com.courseplatform.bean.TeacherCourse;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Component
public interface TeacherCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    @Delete({
        "delete from teacher_course",
        "where course_id = #{courseId,jdbcType=INTEGER}",
          "and teacher_account = #{teacherAccount,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("courseId") Integer courseId, @Param("teacherAccount") String teacherAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    @Insert({
        "insert into teacher_course (course_id, teacher_account, ",
        "courseware)",
        "values (#{courseId,jdbcType=INTEGER}, #{teacherAccount,jdbcType=VARCHAR}, ",
        "#{courseware,jdbcType=VARCHAR})"
    })
    int insert(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    @Select({
        "select",
        "course_id, teacher_account, courseware",
        "from teacher_course",
        "where course_id = #{courseId,jdbcType=INTEGER}",
          "and teacher_account = #{teacherAccount,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="course_id", property="courseId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="teacher_account", property="teacherAccount", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="courseware", property="courseware", jdbcType=JdbcType.VARCHAR)
    })
    TeacherCourse selectByPrimaryKey(@Param("courseId") Integer courseId, @Param("teacherAccount") String teacherAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    @Select({
        "select",
        "course_id, teacher_account, courseware",
        "from teacher_course"
    })
    @Results({
        @Result(column="course_id", property="courseId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="teacher_account", property="teacherAccount", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="courseware", property="courseware", jdbcType=JdbcType.VARCHAR)
    })
    List<TeacherCourse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    @Update({
        "update teacher_course",
        "set courseware = #{courseware,jdbcType=VARCHAR}",
        "where course_id = #{courseId,jdbcType=INTEGER}",
          "and teacher_account = #{teacherAccount,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TeacherCourse record);
}