package com.courseplatform.bean;

import org.apache.ibatis.type.Alias;
import org.springframework.stereotype.Component;

import java.util.Date;

@Alias("Comment")
public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.course_id
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.teacher_acccount
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private String teacherAcccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.student_account
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private String studentAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.time
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.floor
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private Integer floor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.course_id
     *
     * @return the value of comment.course_id
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.course_id
     *
     * @param courseId the value for comment.course_id
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.teacher_acccount
     *
     * @return the value of comment.teacher_acccount
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public String getTeacherAcccount() {
        return teacherAcccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.teacher_acccount
     *
     * @param teacherAcccount the value for comment.teacher_acccount
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setTeacherAcccount(String teacherAcccount) {
        this.teacherAcccount = teacherAcccount == null ? null : teacherAcccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.student_account
     *
     * @return the value of comment.student_account
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public String getStudentAccount() {
        return studentAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.student_account
     *
     * @param studentAccount the value for comment.student_account
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setStudentAccount(String studentAccount) {
        this.studentAccount = studentAccount == null ? null : studentAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.time
     *
     * @return the value of comment.time
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.time
     *
     * @param time the value for comment.time
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.floor
     *
     * @return the value of comment.floor
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.floor
     *
     * @param floor the value for comment.floor
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }
}