package com.courseplatform.bean;

import org.apache.ibatis.type.Alias;

@Alias("Courseware")
public class Courseware {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.courseware_id
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    private String coursewareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.course_id
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.teacher_account
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    private String teacherAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.courseware_name
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    private String coursewareName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.file_path
     *
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    private String filePath;

    public Courseware(String coursewareId, String courseId, String teacherAccount, String coursewareName, String filePath) {
        this.coursewareId = coursewareId;
        this.courseId = courseId;
        this.teacherAccount = teacherAccount;
        this.coursewareName = coursewareName;
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.courseware_id
     *
     * @return the value of courseware.courseware_id
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public String getCoursewareId() {
        return coursewareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.courseware_id
     *
     * @param coursewareId
     *         the value for courseware.courseware_id
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public void setCoursewareId(String coursewareId) {
        this.coursewareId = coursewareId == null ? null : coursewareId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.course_id
     *
     * @return the value of courseware.course_id
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.course_id
     *
     * @param courseId
     *         the value for courseware.course_id
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.teacher_account
     *
     * @return the value of courseware.teacher_account
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public String getTeacherAccount() {
        return teacherAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.teacher_account
     *
     * @param teacherAccount
     *         the value for courseware.teacher_account
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public void setTeacherAccount(String teacherAccount) {
        this.teacherAccount = teacherAccount == null ? null : teacherAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.courseware_name
     *
     * @return the value of courseware.courseware_name
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public String getCoursewareName() {
        return coursewareName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.courseware_name
     *
     * @param coursewareName
     *         the value for courseware.courseware_name
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public void setCoursewareName(String coursewareName) {
        this.coursewareName = coursewareName == null ? null : coursewareName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.file_path
     *
     * @return the value of courseware.file_path
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.file_path
     *
     * @param filePath
     *         the value for courseware.file_path
     * @mbggenerated Wed Dec 14 18:07:59 CST 2016
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    @Override
    public String toString() {
        return "Courseware{" +
                "coursewareId='" + coursewareId + '\'' +
                ", courseId='" + courseId + '\'' +
                ", teacherAccount='" + teacherAccount + '\'' +
                ", coursewareName='" + coursewareName + '\'' +
                ", filePath='" + filePath + '\'' +
                '}';
    }
}