package com.courseplatform.bean;

public class Courseware {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.course_id
     *
     * @mbggenerated Fri Dec 09 21:40:34 CST 2016
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.teacher_account
     *
     * @mbggenerated Fri Dec 09 21:40:34 CST 2016
     */
    private String teacherAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.courseware
     *
     * @mbggenerated Fri Dec 09 21:40:34 CST 2016
     */
    private String courseware;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.course_id
     *
     * @return the value of courseware.course_id
     *
     * @mbggenerated Fri Dec 09 21:40:34 CST 2016
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.course_id
     *
     * @param courseId the value for courseware.course_id
     *
     * @mbggenerated Fri Dec 09 21:40:34 CST 2016
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.teacher_account
     *
     * @return the value of courseware.teacher_account
     *
     * @mbggenerated Fri Dec 09 21:40:34 CST 2016
     */
    public String getTeacherAccount() {
        return teacherAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.teacher_account
     *
     * @param teacherAccount the value for courseware.teacher_account
     *
     * @mbggenerated Fri Dec 09 21:40:34 CST 2016
     */
    public void setTeacherAccount(String teacherAccount) {
        this.teacherAccount = teacherAccount == null ? null : teacherAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.courseware
     *
     * @return the value of courseware.courseware
     *
     * @mbggenerated Fri Dec 09 21:40:34 CST 2016
     */
    public String getCourseware() {
        return courseware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.courseware
     *
     * @param courseware the value for courseware.courseware
     *
     * @mbggenerated Fri Dec 09 21:40:34 CST 2016
     */
    public void setCourseware(String courseware) {
        this.courseware = courseware == null ? null : courseware.trim();
    }
}