package com.courseplatform.bean;

public class StudentCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.course_id
     *
     * @mbggenerated Fri Dec 09 17:24:58 CST 2016
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.teacher_account
     *
     * @mbggenerated Fri Dec 09 17:24:58 CST 2016
     */
    private String teacherAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.student_account
     *
     * @mbggenerated Fri Dec 09 17:24:58 CST 2016
     */
    private String studentAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.course_id
     *
     * @return the value of student_course.course_id
     *
     * @mbggenerated Fri Dec 09 17:24:58 CST 2016
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.course_id
     *
     * @param courseId the value for student_course.course_id
     *
     * @mbggenerated Fri Dec 09 17:24:58 CST 2016
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.teacher_account
     *
     * @return the value of student_course.teacher_account
     *
     * @mbggenerated Fri Dec 09 17:24:58 CST 2016
     */
    public String getTeacherAccount() {
        return teacherAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.teacher_account
     *
     * @param teacherAccount the value for student_course.teacher_account
     *
     * @mbggenerated Fri Dec 09 17:24:58 CST 2016
     */
    public void setTeacherAccount(String teacherAccount) {
        this.teacherAccount = teacherAccount == null ? null : teacherAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.student_account
     *
     * @return the value of student_course.student_account
     *
     * @mbggenerated Fri Dec 09 17:24:58 CST 2016
     */
    public String getStudentAccount() {
        return studentAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.student_account
     *
     * @param studentAccount the value for student_course.student_account
     *
     * @mbggenerated Fri Dec 09 17:24:58 CST 2016
     */
    public void setStudentAccount(String studentAccount) {
        this.studentAccount = studentAccount == null ? null : studentAccount.trim();
    }
}