package com.courseplatform.bean;

import org.apache.ibatis.type.Alias;
import org.springframework.stereotype.Component;

@Alias("TeacherCourse")
public class TeacherCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course.course_id
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course.teacher_account
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private String teacherAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course.courseware
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    private String courseware;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course.course_id
     *
     * @return the value of teacher_course.course_id
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course.course_id
     *
     * @param courseId the value for teacher_course.course_id
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course.teacher_account
     *
     * @return the value of teacher_course.teacher_account
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public String getTeacherAccount() {
        return teacherAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course.teacher_account
     *
     * @param teacherAccount the value for teacher_course.teacher_account
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setTeacherAccount(String teacherAccount) {
        this.teacherAccount = teacherAccount == null ? null : teacherAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course.courseware
     *
     * @return the value of teacher_course.courseware
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public String getCourseware() {
        return courseware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course.courseware
     *
     * @param courseware the value for teacher_course.courseware
     *
     * @mbggenerated Thu Dec 08 11:15:00 CST 2016
     */
    public void setCourseware(String courseware) {
        this.courseware = courseware == null ? null : courseware.trim();
    }
}